apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-server
  template:
    metadata:
      labels:
        app: cicd-server
    spec:
      containers:
        - name: cicd-server-container
          image: lichanyeok/cicdsource:9433f1d468fba41254566f92f1d30abd776b6266
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-service
spec:
  type: NodePort
  selector:
    app: cicd-server
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 8080
      targetPort: 8080
