apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-server
  template:
    metadata:
      labels:
        app: cicd-server
    spec:
      containers:
        - name: cicd-server-container
          image: lichanyeok/cicdsource:e555045cd433003fe1cd872abf221e79bf2b7787
          ports:
            - containerPort: 8080
