apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-server
  template:
    metadata:
      labels:
        app: cicd-server
    spec:
      containers:
        - name: cicd-server-container
          image: lichanyeok/cicdsource:e070c37b58063a4461f57f8fa5db3a46bf15247f
          ports:
            - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: cicd-service
spec:
  type: NodePort
  selector:
    app: cicd-server
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 8080
      targetPort: 8080


